### ISSUE TITLE
Unable to build with go 1.17.4

### ISSUE THREAD

**Issue by marek-obuchowicz** [benkeil/hydra#2]
I'm getting following error while trying to build with new version of golang:
```
 /go/pkg/mod/github.com/golang/dep@v0.5.4/gps/constraint.go:103:21: cannot use sv (type *semver.Version) as type semver.Version in field value
 /go/pkg/mod/github.com/golang/dep@v0.5.4/gps/constraint.go:122:16: invalid type assertion: c.(semver.Version) (non-interface type *semver.Constraints on left)
 /go/pkg/mod/github.com/golang/dep@v0.5.4/gps/constraint.go:149:4: undefined: semver.Constraint
```

any hints how to solve dependency issue?

**Comment by marek-obuchowicz** [comment]
Please disregard, was pre go1.11 module approach, `dep` not needed anymore
